package it.fivano.symusic.backend.model;

import java.io.Serializable;

public class ReleaseLink implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_link.id_release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    private Long idReleaseLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_link.id_release
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    private Long idRelease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_link.release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    private String releaseLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_link.id_release_link
     *
     * @return the value of release_link.id_release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public Long getIdReleaseLink() {
        return idReleaseLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_link.id_release_link
     *
     * @param idReleaseLink the value for release_link.id_release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public void setIdReleaseLink(Long idReleaseLink) {
        this.idReleaseLink = idReleaseLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_link.id_release
     *
     * @return the value of release_link.id_release
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public Long getIdRelease() {
        return idRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_link.id_release
     *
     * @param idRelease the value for release_link.id_release
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public void setIdRelease(Long idRelease) {
        this.idRelease = idRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_link.release_link
     *
     * @return the value of release_link.release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public String getReleaseLink() {
        return releaseLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_link.release_link
     *
     * @param releaseLink the value for release_link.release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public void setReleaseLink(String releaseLink) {
        this.releaseLink = releaseLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ReleaseLink other = (ReleaseLink) that;
        return (this.getIdReleaseLink() == null ? other.getIdReleaseLink() == null : this.getIdReleaseLink().equals(other.getIdReleaseLink()))
            && (this.getIdRelease() == null ? other.getIdRelease() == null : this.getIdRelease().equals(other.getIdRelease()))
            && (this.getReleaseLink() == null ? other.getReleaseLink() == null : this.getReleaseLink().equals(other.getReleaseLink()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdReleaseLink() == null) ? 0 : getIdReleaseLink().hashCode());
        result = prime * result + ((getIdRelease() == null) ? 0 : getIdRelease().hashCode());
        result = prime * result + ((getReleaseLink() == null) ? 0 : getReleaseLink().hashCode());
        return result;
    }
}