package it.fivano.symusic.backend.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ReleaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public ReleaseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdReleaseIsNull() {
            addCriterion("id_release is null");
            return (Criteria) this;
        }

        public Criteria andIdReleaseIsNotNull() {
            addCriterion("id_release is not null");
            return (Criteria) this;
        }

        public Criteria andIdReleaseEqualTo(Long value) {
            addCriterion("id_release =", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseNotEqualTo(Long value) {
            addCriterion("id_release <>", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseGreaterThan(Long value) {
            addCriterion("id_release >", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseGreaterThanOrEqualTo(Long value) {
            addCriterion("id_release >=", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseLessThan(Long value) {
            addCriterion("id_release <", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseLessThanOrEqualTo(Long value) {
            addCriterion("id_release <=", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseIn(List<Long> values) {
            addCriterion("id_release in", values, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseNotIn(List<Long> values) {
            addCriterion("id_release not in", values, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseBetween(Long value1, Long value2) {
            addCriterion("id_release between", value1, value2, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseNotBetween(Long value1, Long value2) {
            addCriterion("id_release not between", value1, value2, "idRelease");
            return (Criteria) this;
        }

        public Criteria andReleaseNameIsNull() {
            addCriterion("release_name is null");
            return (Criteria) this;
        }

        public Criteria andReleaseNameIsNotNull() {
            addCriterion("release_name is not null");
            return (Criteria) this;
        }

        public Criteria andReleaseNameEqualTo(String value) {
            addCriterion("release_name =", value, "releaseName");
            return (Criteria) this;
        }

        public Criteria andReleaseNameNotEqualTo(String value) {
            addCriterion("release_name <>", value, "releaseName");
            return (Criteria) this;
        }

        public Criteria andReleaseNameGreaterThan(String value) {
            addCriterion("release_name >", value, "releaseName");
            return (Criteria) this;
        }

        public Criteria andReleaseNameGreaterThanOrEqualTo(String value) {
            addCriterion("release_name >=", value, "releaseName");
            return (Criteria) this;
        }

        public Criteria andReleaseNameLessThan(String value) {
            addCriterion("release_name <", value, "releaseName");
            return (Criteria) this;
        }

        public Criteria andReleaseNameLessThanOrEqualTo(String value) {
            addCriterion("release_name <=", value, "releaseName");
            return (Criteria) this;
        }

        public Criteria andReleaseNameLike(String value) {
            addCriterion("release_name like", value, "releaseName");
            return (Criteria) this;
        }

        public Criteria andReleaseNameNotLike(String value) {
            addCriterion("release_name not like", value, "releaseName");
            return (Criteria) this;
        }

        public Criteria andReleaseNameIn(List<String> values) {
            addCriterion("release_name in", values, "releaseName");
            return (Criteria) this;
        }

        public Criteria andReleaseNameNotIn(List<String> values) {
            addCriterion("release_name not in", values, "releaseName");
            return (Criteria) this;
        }

        public Criteria andReleaseNameBetween(String value1, String value2) {
            addCriterion("release_name between", value1, value2, "releaseName");
            return (Criteria) this;
        }

        public Criteria andReleaseNameNotBetween(String value1, String value2) {
            addCriterion("release_name not between", value1, value2, "releaseName");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("author is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("author is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(String value) {
            addCriterion("author =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(String value) {
            addCriterion("author <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(String value) {
            addCriterion("author >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("author >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(String value) {
            addCriterion("author <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(String value) {
            addCriterion("author <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLike(String value) {
            addCriterion("author like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotLike(String value) {
            addCriterion("author not like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<String> values) {
            addCriterion("author in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<String> values) {
            addCriterion("author not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(String value1, String value2) {
            addCriterion("author between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(String value1, String value2) {
            addCriterion("author not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andSongNameIsNull() {
            addCriterion("song_name is null");
            return (Criteria) this;
        }

        public Criteria andSongNameIsNotNull() {
            addCriterion("song_name is not null");
            return (Criteria) this;
        }

        public Criteria andSongNameEqualTo(String value) {
            addCriterion("song_name =", value, "songName");
            return (Criteria) this;
        }

        public Criteria andSongNameNotEqualTo(String value) {
            addCriterion("song_name <>", value, "songName");
            return (Criteria) this;
        }

        public Criteria andSongNameGreaterThan(String value) {
            addCriterion("song_name >", value, "songName");
            return (Criteria) this;
        }

        public Criteria andSongNameGreaterThanOrEqualTo(String value) {
            addCriterion("song_name >=", value, "songName");
            return (Criteria) this;
        }

        public Criteria andSongNameLessThan(String value) {
            addCriterion("song_name <", value, "songName");
            return (Criteria) this;
        }

        public Criteria andSongNameLessThanOrEqualTo(String value) {
            addCriterion("song_name <=", value, "songName");
            return (Criteria) this;
        }

        public Criteria andSongNameLike(String value) {
            addCriterion("song_name like", value, "songName");
            return (Criteria) this;
        }

        public Criteria andSongNameNotLike(String value) {
            addCriterion("song_name not like", value, "songName");
            return (Criteria) this;
        }

        public Criteria andSongNameIn(List<String> values) {
            addCriterion("song_name in", values, "songName");
            return (Criteria) this;
        }

        public Criteria andSongNameNotIn(List<String> values) {
            addCriterion("song_name not in", values, "songName");
            return (Criteria) this;
        }

        public Criteria andSongNameBetween(String value1, String value2) {
            addCriterion("song_name between", value1, value2, "songName");
            return (Criteria) this;
        }

        public Criteria andSongNameNotBetween(String value1, String value2) {
            addCriterion("song_name not between", value1, value2, "songName");
            return (Criteria) this;
        }

        public Criteria andYearsIsNull() {
            addCriterion("years is null");
            return (Criteria) this;
        }

        public Criteria andYearsIsNotNull() {
            addCriterion("years is not null");
            return (Criteria) this;
        }

        public Criteria andYearsEqualTo(String value) {
            addCriterion("years =", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsNotEqualTo(String value) {
            addCriterion("years <>", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsGreaterThan(String value) {
            addCriterion("years >", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsGreaterThanOrEqualTo(String value) {
            addCriterion("years >=", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsLessThan(String value) {
            addCriterion("years <", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsLessThanOrEqualTo(String value) {
            addCriterion("years <=", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsLike(String value) {
            addCriterion("years like", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsNotLike(String value) {
            addCriterion("years not like", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsIn(List<String> values) {
            addCriterion("years in", values, "years");
            return (Criteria) this;
        }

        public Criteria andYearsNotIn(List<String> values) {
            addCriterion("years not in", values, "years");
            return (Criteria) this;
        }

        public Criteria andYearsBetween(String value1, String value2) {
            addCriterion("years between", value1, value2, "years");
            return (Criteria) this;
        }

        public Criteria andYearsNotBetween(String value1, String value2) {
            addCriterion("years not between", value1, value2, "years");
            return (Criteria) this;
        }

        public Criteria andCrewIsNull() {
            addCriterion("crew is null");
            return (Criteria) this;
        }

        public Criteria andCrewIsNotNull() {
            addCriterion("crew is not null");
            return (Criteria) this;
        }

        public Criteria andCrewEqualTo(String value) {
            addCriterion("crew =", value, "crew");
            return (Criteria) this;
        }

        public Criteria andCrewNotEqualTo(String value) {
            addCriterion("crew <>", value, "crew");
            return (Criteria) this;
        }

        public Criteria andCrewGreaterThan(String value) {
            addCriterion("crew >", value, "crew");
            return (Criteria) this;
        }

        public Criteria andCrewGreaterThanOrEqualTo(String value) {
            addCriterion("crew >=", value, "crew");
            return (Criteria) this;
        }

        public Criteria andCrewLessThan(String value) {
            addCriterion("crew <", value, "crew");
            return (Criteria) this;
        }

        public Criteria andCrewLessThanOrEqualTo(String value) {
            addCriterion("crew <=", value, "crew");
            return (Criteria) this;
        }

        public Criteria andCrewLike(String value) {
            addCriterion("crew like", value, "crew");
            return (Criteria) this;
        }

        public Criteria andCrewNotLike(String value) {
            addCriterion("crew not like", value, "crew");
            return (Criteria) this;
        }

        public Criteria andCrewIn(List<String> values) {
            addCriterion("crew in", values, "crew");
            return (Criteria) this;
        }

        public Criteria andCrewNotIn(List<String> values) {
            addCriterion("crew not in", values, "crew");
            return (Criteria) this;
        }

        public Criteria andCrewBetween(String value1, String value2) {
            addCriterion("crew between", value1, value2, "crew");
            return (Criteria) this;
        }

        public Criteria andCrewNotBetween(String value1, String value2) {
            addCriterion("crew not between", value1, value2, "crew");
            return (Criteria) this;
        }

        public Criteria andReleaseDateIsNull() {
            addCriterion("release_date is null");
            return (Criteria) this;
        }

        public Criteria andReleaseDateIsNotNull() {
            addCriterion("release_date is not null");
            return (Criteria) this;
        }

        public Criteria andReleaseDateEqualTo(Date value) {
            addCriterionForJDBCDate("release_date =", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("release_date <>", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateGreaterThan(Date value) {
            addCriterionForJDBCDate("release_date >", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("release_date >=", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateLessThan(Date value) {
            addCriterionForJDBCDate("release_date <", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("release_date <=", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateIn(List<Date> values) {
            addCriterionForJDBCDate("release_date in", values, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("release_date not in", values, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("release_date between", value1, value2, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("release_date not between", value1, value2, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andIdGenreIsNull() {
            addCriterion("id_genre is null");
            return (Criteria) this;
        }

        public Criteria andIdGenreIsNotNull() {
            addCriterion("id_genre is not null");
            return (Criteria) this;
        }

        public Criteria andIdGenreEqualTo(Integer value) {
            addCriterion("id_genre =", value, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreNotEqualTo(Integer value) {
            addCriterion("id_genre <>", value, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreGreaterThan(Integer value) {
            addCriterion("id_genre >", value, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_genre >=", value, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreLessThan(Integer value) {
            addCriterion("id_genre <", value, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreLessThanOrEqualTo(Integer value) {
            addCriterion("id_genre <=", value, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreIn(List<Integer> values) {
            addCriterion("id_genre in", values, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreNotIn(List<Integer> values) {
            addCriterion("id_genre not in", values, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreBetween(Integer value1, Integer value2) {
            addCriterion("id_genre between", value1, value2, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreNotBetween(Integer value1, Integer value2) {
            addCriterion("id_genre not between", value1, value2, "idGenre");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table symusic..release
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 09 23:38:11 CEST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}