package it.fivano.symusic.backend.model;

import java.util.ArrayList;
import java.util.List;

public class ReleaseTrackExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public ReleaseTrackExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdReleaseTrackIsNull() {
            addCriterion("id_release_track is null");
            return (Criteria) this;
        }

        public Criteria andIdReleaseTrackIsNotNull() {
            addCriterion("id_release_track is not null");
            return (Criteria) this;
        }

        public Criteria andIdReleaseTrackEqualTo(Long value) {
            addCriterion("id_release_track =", value, "idReleaseTrack");
            return (Criteria) this;
        }

        public Criteria andIdReleaseTrackNotEqualTo(Long value) {
            addCriterion("id_release_track <>", value, "idReleaseTrack");
            return (Criteria) this;
        }

        public Criteria andIdReleaseTrackGreaterThan(Long value) {
            addCriterion("id_release_track >", value, "idReleaseTrack");
            return (Criteria) this;
        }

        public Criteria andIdReleaseTrackGreaterThanOrEqualTo(Long value) {
            addCriterion("id_release_track >=", value, "idReleaseTrack");
            return (Criteria) this;
        }

        public Criteria andIdReleaseTrackLessThan(Long value) {
            addCriterion("id_release_track <", value, "idReleaseTrack");
            return (Criteria) this;
        }

        public Criteria andIdReleaseTrackLessThanOrEqualTo(Long value) {
            addCriterion("id_release_track <=", value, "idReleaseTrack");
            return (Criteria) this;
        }

        public Criteria andIdReleaseTrackIn(List<Long> values) {
            addCriterion("id_release_track in", values, "idReleaseTrack");
            return (Criteria) this;
        }

        public Criteria andIdReleaseTrackNotIn(List<Long> values) {
            addCriterion("id_release_track not in", values, "idReleaseTrack");
            return (Criteria) this;
        }

        public Criteria andIdReleaseTrackBetween(Long value1, Long value2) {
            addCriterion("id_release_track between", value1, value2, "idReleaseTrack");
            return (Criteria) this;
        }

        public Criteria andIdReleaseTrackNotBetween(Long value1, Long value2) {
            addCriterion("id_release_track not between", value1, value2, "idReleaseTrack");
            return (Criteria) this;
        }

        public Criteria andIdReleaseIsNull() {
            addCriterion("id_release is null");
            return (Criteria) this;
        }

        public Criteria andIdReleaseIsNotNull() {
            addCriterion("id_release is not null");
            return (Criteria) this;
        }

        public Criteria andIdReleaseEqualTo(Long value) {
            addCriterion("id_release =", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseNotEqualTo(Long value) {
            addCriterion("id_release <>", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseGreaterThan(Long value) {
            addCriterion("id_release >", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseGreaterThanOrEqualTo(Long value) {
            addCriterion("id_release >=", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseLessThan(Long value) {
            addCriterion("id_release <", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseLessThanOrEqualTo(Long value) {
            addCriterion("id_release <=", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseIn(List<Long> values) {
            addCriterion("id_release in", values, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseNotIn(List<Long> values) {
            addCriterion("id_release not in", values, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseBetween(Long value1, Long value2) {
            addCriterion("id_release between", value1, value2, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseNotBetween(Long value1, Long value2) {
            addCriterion("id_release not between", value1, value2, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdGenreIsNull() {
            addCriterion("id_genre is null");
            return (Criteria) this;
        }

        public Criteria andIdGenreIsNotNull() {
            addCriterion("id_genre is not null");
            return (Criteria) this;
        }

        public Criteria andIdGenreEqualTo(Integer value) {
            addCriterion("id_genre =", value, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreNotEqualTo(Integer value) {
            addCriterion("id_genre <>", value, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreGreaterThan(Integer value) {
            addCriterion("id_genre >", value, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_genre >=", value, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreLessThan(Integer value) {
            addCriterion("id_genre <", value, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreLessThanOrEqualTo(Integer value) {
            addCriterion("id_genre <=", value, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreIn(List<Integer> values) {
            addCriterion("id_genre in", values, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreNotIn(List<Integer> values) {
            addCriterion("id_genre not in", values, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreBetween(Integer value1, Integer value2) {
            addCriterion("id_genre between", value1, value2, "idGenre");
            return (Criteria) this;
        }

        public Criteria andIdGenreNotBetween(Integer value1, Integer value2) {
            addCriterion("id_genre not between", value1, value2, "idGenre");
            return (Criteria) this;
        }

        public Criteria andTrackNumberIsNull() {
            addCriterion("track_number is null");
            return (Criteria) this;
        }

        public Criteria andTrackNumberIsNotNull() {
            addCriterion("track_number is not null");
            return (Criteria) this;
        }

        public Criteria andTrackNumberEqualTo(String value) {
            addCriterion("track_number =", value, "trackNumber");
            return (Criteria) this;
        }

        public Criteria andTrackNumberNotEqualTo(String value) {
            addCriterion("track_number <>", value, "trackNumber");
            return (Criteria) this;
        }

        public Criteria andTrackNumberGreaterThan(String value) {
            addCriterion("track_number >", value, "trackNumber");
            return (Criteria) this;
        }

        public Criteria andTrackNumberGreaterThanOrEqualTo(String value) {
            addCriterion("track_number >=", value, "trackNumber");
            return (Criteria) this;
        }

        public Criteria andTrackNumberLessThan(String value) {
            addCriterion("track_number <", value, "trackNumber");
            return (Criteria) this;
        }

        public Criteria andTrackNumberLessThanOrEqualTo(String value) {
            addCriterion("track_number <=", value, "trackNumber");
            return (Criteria) this;
        }

        public Criteria andTrackNumberLike(String value) {
            addCriterion("track_number like", value, "trackNumber");
            return (Criteria) this;
        }

        public Criteria andTrackNumberNotLike(String value) {
            addCriterion("track_number not like", value, "trackNumber");
            return (Criteria) this;
        }

        public Criteria andTrackNumberIn(List<String> values) {
            addCriterion("track_number in", values, "trackNumber");
            return (Criteria) this;
        }

        public Criteria andTrackNumberNotIn(List<String> values) {
            addCriterion("track_number not in", values, "trackNumber");
            return (Criteria) this;
        }

        public Criteria andTrackNumberBetween(String value1, String value2) {
            addCriterion("track_number between", value1, value2, "trackNumber");
            return (Criteria) this;
        }

        public Criteria andTrackNumberNotBetween(String value1, String value2) {
            addCriterion("track_number not between", value1, value2, "trackNumber");
            return (Criteria) this;
        }

        public Criteria andTrackNameIsNull() {
            addCriterion("track_name is null");
            return (Criteria) this;
        }

        public Criteria andTrackNameIsNotNull() {
            addCriterion("track_name is not null");
            return (Criteria) this;
        }

        public Criteria andTrackNameEqualTo(String value) {
            addCriterion("track_name =", value, "trackName");
            return (Criteria) this;
        }

        public Criteria andTrackNameNotEqualTo(String value) {
            addCriterion("track_name <>", value, "trackName");
            return (Criteria) this;
        }

        public Criteria andTrackNameGreaterThan(String value) {
            addCriterion("track_name >", value, "trackName");
            return (Criteria) this;
        }

        public Criteria andTrackNameGreaterThanOrEqualTo(String value) {
            addCriterion("track_name >=", value, "trackName");
            return (Criteria) this;
        }

        public Criteria andTrackNameLessThan(String value) {
            addCriterion("track_name <", value, "trackName");
            return (Criteria) this;
        }

        public Criteria andTrackNameLessThanOrEqualTo(String value) {
            addCriterion("track_name <=", value, "trackName");
            return (Criteria) this;
        }

        public Criteria andTrackNameLike(String value) {
            addCriterion("track_name like", value, "trackName");
            return (Criteria) this;
        }

        public Criteria andTrackNameNotLike(String value) {
            addCriterion("track_name not like", value, "trackName");
            return (Criteria) this;
        }

        public Criteria andTrackNameIn(List<String> values) {
            addCriterion("track_name in", values, "trackName");
            return (Criteria) this;
        }

        public Criteria andTrackNameNotIn(List<String> values) {
            addCriterion("track_name not in", values, "trackName");
            return (Criteria) this;
        }

        public Criteria andTrackNameBetween(String value1, String value2) {
            addCriterion("track_name between", value1, value2, "trackName");
            return (Criteria) this;
        }

        public Criteria andTrackNameNotBetween(String value1, String value2) {
            addCriterion("track_name not between", value1, value2, "trackName");
            return (Criteria) this;
        }

        public Criteria andTrackTimeIsNull() {
            addCriterion("track_time is null");
            return (Criteria) this;
        }

        public Criteria andTrackTimeIsNotNull() {
            addCriterion("track_time is not null");
            return (Criteria) this;
        }

        public Criteria andTrackTimeEqualTo(String value) {
            addCriterion("track_time =", value, "trackTime");
            return (Criteria) this;
        }

        public Criteria andTrackTimeNotEqualTo(String value) {
            addCriterion("track_time <>", value, "trackTime");
            return (Criteria) this;
        }

        public Criteria andTrackTimeGreaterThan(String value) {
            addCriterion("track_time >", value, "trackTime");
            return (Criteria) this;
        }

        public Criteria andTrackTimeGreaterThanOrEqualTo(String value) {
            addCriterion("track_time >=", value, "trackTime");
            return (Criteria) this;
        }

        public Criteria andTrackTimeLessThan(String value) {
            addCriterion("track_time <", value, "trackTime");
            return (Criteria) this;
        }

        public Criteria andTrackTimeLessThanOrEqualTo(String value) {
            addCriterion("track_time <=", value, "trackTime");
            return (Criteria) this;
        }

        public Criteria andTrackTimeLike(String value) {
            addCriterion("track_time like", value, "trackTime");
            return (Criteria) this;
        }

        public Criteria andTrackTimeNotLike(String value) {
            addCriterion("track_time not like", value, "trackTime");
            return (Criteria) this;
        }

        public Criteria andTrackTimeIn(List<String> values) {
            addCriterion("track_time in", values, "trackTime");
            return (Criteria) this;
        }

        public Criteria andTrackTimeNotIn(List<String> values) {
            addCriterion("track_time not in", values, "trackTime");
            return (Criteria) this;
        }

        public Criteria andTrackTimeBetween(String value1, String value2) {
            addCriterion("track_time between", value1, value2, "trackTime");
            return (Criteria) this;
        }

        public Criteria andTrackTimeNotBetween(String value1, String value2) {
            addCriterion("track_time not between", value1, value2, "trackTime");
            return (Criteria) this;
        }

        public Criteria andTrackBpmIsNull() {
            addCriterion("track_bpm is null");
            return (Criteria) this;
        }

        public Criteria andTrackBpmIsNotNull() {
            addCriterion("track_bpm is not null");
            return (Criteria) this;
        }

        public Criteria andTrackBpmEqualTo(String value) {
            addCriterion("track_bpm =", value, "trackBpm");
            return (Criteria) this;
        }

        public Criteria andTrackBpmNotEqualTo(String value) {
            addCriterion("track_bpm <>", value, "trackBpm");
            return (Criteria) this;
        }

        public Criteria andTrackBpmGreaterThan(String value) {
            addCriterion("track_bpm >", value, "trackBpm");
            return (Criteria) this;
        }

        public Criteria andTrackBpmGreaterThanOrEqualTo(String value) {
            addCriterion("track_bpm >=", value, "trackBpm");
            return (Criteria) this;
        }

        public Criteria andTrackBpmLessThan(String value) {
            addCriterion("track_bpm <", value, "trackBpm");
            return (Criteria) this;
        }

        public Criteria andTrackBpmLessThanOrEqualTo(String value) {
            addCriterion("track_bpm <=", value, "trackBpm");
            return (Criteria) this;
        }

        public Criteria andTrackBpmLike(String value) {
            addCriterion("track_bpm like", value, "trackBpm");
            return (Criteria) this;
        }

        public Criteria andTrackBpmNotLike(String value) {
            addCriterion("track_bpm not like", value, "trackBpm");
            return (Criteria) this;
        }

        public Criteria andTrackBpmIn(List<String> values) {
            addCriterion("track_bpm in", values, "trackBpm");
            return (Criteria) this;
        }

        public Criteria andTrackBpmNotIn(List<String> values) {
            addCriterion("track_bpm not in", values, "trackBpm");
            return (Criteria) this;
        }

        public Criteria andTrackBpmBetween(String value1, String value2) {
            addCriterion("track_bpm between", value1, value2, "trackBpm");
            return (Criteria) this;
        }

        public Criteria andTrackBpmNotBetween(String value1, String value2) {
            addCriterion("track_bpm not between", value1, value2, "trackBpm");
            return (Criteria) this;
        }

        public Criteria andTrackGenereIsNull() {
            addCriterion("track_genere is null");
            return (Criteria) this;
        }

        public Criteria andTrackGenereIsNotNull() {
            addCriterion("track_genere is not null");
            return (Criteria) this;
        }

        public Criteria andTrackGenereEqualTo(String value) {
            addCriterion("track_genere =", value, "trackGenere");
            return (Criteria) this;
        }

        public Criteria andTrackGenereNotEqualTo(String value) {
            addCriterion("track_genere <>", value, "trackGenere");
            return (Criteria) this;
        }

        public Criteria andTrackGenereGreaterThan(String value) {
            addCriterion("track_genere >", value, "trackGenere");
            return (Criteria) this;
        }

        public Criteria andTrackGenereGreaterThanOrEqualTo(String value) {
            addCriterion("track_genere >=", value, "trackGenere");
            return (Criteria) this;
        }

        public Criteria andTrackGenereLessThan(String value) {
            addCriterion("track_genere <", value, "trackGenere");
            return (Criteria) this;
        }

        public Criteria andTrackGenereLessThanOrEqualTo(String value) {
            addCriterion("track_genere <=", value, "trackGenere");
            return (Criteria) this;
        }

        public Criteria andTrackGenereLike(String value) {
            addCriterion("track_genere like", value, "trackGenere");
            return (Criteria) this;
        }

        public Criteria andTrackGenereNotLike(String value) {
            addCriterion("track_genere not like", value, "trackGenere");
            return (Criteria) this;
        }

        public Criteria andTrackGenereIn(List<String> values) {
            addCriterion("track_genere in", values, "trackGenere");
            return (Criteria) this;
        }

        public Criteria andTrackGenereNotIn(List<String> values) {
            addCriterion("track_genere not in", values, "trackGenere");
            return (Criteria) this;
        }

        public Criteria andTrackGenereBetween(String value1, String value2) {
            addCriterion("track_genere between", value1, value2, "trackGenere");
            return (Criteria) this;
        }

        public Criteria andTrackGenereNotBetween(String value1, String value2) {
            addCriterion("track_genere not between", value1, value2, "trackGenere");
            return (Criteria) this;
        }

        public Criteria andTagIsNull() {
            addCriterion("tag is null");
            return (Criteria) this;
        }

        public Criteria andTagIsNotNull() {
            addCriterion("tag is not null");
            return (Criteria) this;
        }

        public Criteria andTagEqualTo(String value) {
            addCriterion("tag =", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotEqualTo(String value) {
            addCriterion("tag <>", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThan(String value) {
            addCriterion("tag >", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThanOrEqualTo(String value) {
            addCriterion("tag >=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThan(String value) {
            addCriterion("tag <", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThanOrEqualTo(String value) {
            addCriterion("tag <=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLike(String value) {
            addCriterion("tag like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotLike(String value) {
            addCriterion("tag not like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagIn(List<String> values) {
            addCriterion("tag in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotIn(List<String> values) {
            addCriterion("tag not in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagBetween(String value1, String value2) {
            addCriterion("tag between", value1, value2, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotBetween(String value1, String value2) {
            addCriterion("tag not between", value1, value2, "tag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table release_track
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 01 01:31:17 CEST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table release_track
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}