package it.fivano.symusic.backend.model;

import java.util.ArrayList;
import java.util.List;

public class ReleaseVideoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public ReleaseVideoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdReleaseVideoIsNull() {
            addCriterion("id_release_video is null");
            return (Criteria) this;
        }

        public Criteria andIdReleaseVideoIsNotNull() {
            addCriterion("id_release_video is not null");
            return (Criteria) this;
        }

        public Criteria andIdReleaseVideoEqualTo(Long value) {
            addCriterion("id_release_video =", value, "idReleaseVideo");
            return (Criteria) this;
        }

        public Criteria andIdReleaseVideoNotEqualTo(Long value) {
            addCriterion("id_release_video <>", value, "idReleaseVideo");
            return (Criteria) this;
        }

        public Criteria andIdReleaseVideoGreaterThan(Long value) {
            addCriterion("id_release_video >", value, "idReleaseVideo");
            return (Criteria) this;
        }

        public Criteria andIdReleaseVideoGreaterThanOrEqualTo(Long value) {
            addCriterion("id_release_video >=", value, "idReleaseVideo");
            return (Criteria) this;
        }

        public Criteria andIdReleaseVideoLessThan(Long value) {
            addCriterion("id_release_video <", value, "idReleaseVideo");
            return (Criteria) this;
        }

        public Criteria andIdReleaseVideoLessThanOrEqualTo(Long value) {
            addCriterion("id_release_video <=", value, "idReleaseVideo");
            return (Criteria) this;
        }

        public Criteria andIdReleaseVideoIn(List<Long> values) {
            addCriterion("id_release_video in", values, "idReleaseVideo");
            return (Criteria) this;
        }

        public Criteria andIdReleaseVideoNotIn(List<Long> values) {
            addCriterion("id_release_video not in", values, "idReleaseVideo");
            return (Criteria) this;
        }

        public Criteria andIdReleaseVideoBetween(Long value1, Long value2) {
            addCriterion("id_release_video between", value1, value2, "idReleaseVideo");
            return (Criteria) this;
        }

        public Criteria andIdReleaseVideoNotBetween(Long value1, Long value2) {
            addCriterion("id_release_video not between", value1, value2, "idReleaseVideo");
            return (Criteria) this;
        }

        public Criteria andIdReleaseIsNull() {
            addCriterion("id_release is null");
            return (Criteria) this;
        }

        public Criteria andIdReleaseIsNotNull() {
            addCriterion("id_release is not null");
            return (Criteria) this;
        }

        public Criteria andIdReleaseEqualTo(Long value) {
            addCriterion("id_release =", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseNotEqualTo(Long value) {
            addCriterion("id_release <>", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseGreaterThan(Long value) {
            addCriterion("id_release >", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseGreaterThanOrEqualTo(Long value) {
            addCriterion("id_release >=", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseLessThan(Long value) {
            addCriterion("id_release <", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseLessThanOrEqualTo(Long value) {
            addCriterion("id_release <=", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseIn(List<Long> values) {
            addCriterion("id_release in", values, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseNotIn(List<Long> values) {
            addCriterion("id_release not in", values, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseBetween(Long value1, Long value2) {
            addCriterion("id_release between", value1, value2, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseNotBetween(Long value1, Long value2) {
            addCriterion("id_release not between", value1, value2, "idRelease");
            return (Criteria) this;
        }

        public Criteria andVideoLinkIsNull() {
            addCriterion("video_link is null");
            return (Criteria) this;
        }

        public Criteria andVideoLinkIsNotNull() {
            addCriterion("video_link is not null");
            return (Criteria) this;
        }

        public Criteria andVideoLinkEqualTo(String value) {
            addCriterion("video_link =", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkNotEqualTo(String value) {
            addCriterion("video_link <>", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkGreaterThan(String value) {
            addCriterion("video_link >", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkGreaterThanOrEqualTo(String value) {
            addCriterion("video_link >=", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkLessThan(String value) {
            addCriterion("video_link <", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkLessThanOrEqualTo(String value) {
            addCriterion("video_link <=", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkLike(String value) {
            addCriterion("video_link like", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkNotLike(String value) {
            addCriterion("video_link not like", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkIn(List<String> values) {
            addCriterion("video_link in", values, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkNotIn(List<String> values) {
            addCriterion("video_link not in", values, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkBetween(String value1, String value2) {
            addCriterion("video_link between", value1, value2, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkNotBetween(String value1, String value2) {
            addCriterion("video_link not between", value1, value2, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoNameIsNull() {
            addCriterion("video_name is null");
            return (Criteria) this;
        }

        public Criteria andVideoNameIsNotNull() {
            addCriterion("video_name is not null");
            return (Criteria) this;
        }

        public Criteria andVideoNameEqualTo(String value) {
            addCriterion("video_name =", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotEqualTo(String value) {
            addCriterion("video_name <>", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameGreaterThan(String value) {
            addCriterion("video_name >", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameGreaterThanOrEqualTo(String value) {
            addCriterion("video_name >=", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLessThan(String value) {
            addCriterion("video_name <", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLessThanOrEqualTo(String value) {
            addCriterion("video_name <=", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLike(String value) {
            addCriterion("video_name like", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotLike(String value) {
            addCriterion("video_name not like", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameIn(List<String> values) {
            addCriterion("video_name in", values, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotIn(List<String> values) {
            addCriterion("video_name not in", values, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameBetween(String value1, String value2) {
            addCriterion("video_name between", value1, value2, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotBetween(String value1, String value2) {
            addCriterion("video_name not between", value1, value2, "videoName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table symusic..release_video
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 09 23:13:41 CEST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}