package it.fivano.symusic.backend.model;

import java.io.Serializable;

public class ReleaseUserOption extends ReleaseUserOptionKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column symusic..release_user_option.release_downloaded
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    private Boolean releaseDownloaded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column symusic..release_user_option.release_preview
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    private Boolean releasePreview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column symusic..release_user_option.release_downloaded
     *
     * @return the value of symusic..release_user_option.release_downloaded
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    public Boolean getReleaseDownloaded() {
        return releaseDownloaded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column symusic..release_user_option.release_downloaded
     *
     * @param releaseDownloaded the value for symusic..release_user_option.release_downloaded
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    public void setReleaseDownloaded(Boolean releaseDownloaded) {
        this.releaseDownloaded = releaseDownloaded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column symusic..release_user_option.release_preview
     *
     * @return the value of symusic..release_user_option.release_preview
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    public Boolean getReleasePreview() {
        return releasePreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column symusic..release_user_option.release_preview
     *
     * @param releasePreview the value for symusic..release_user_option.release_preview
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    public void setReleasePreview(Boolean releasePreview) {
        this.releasePreview = releasePreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ReleaseUserOption other = (ReleaseUserOption) that;
        return (this.getIdRelease() == null ? other.getIdRelease() == null : this.getIdRelease().equals(other.getIdRelease()))
            && (this.getIdUser() == null ? other.getIdUser() == null : this.getIdUser().equals(other.getIdUser()))
            && (this.getReleaseDownloaded() == null ? other.getReleaseDownloaded() == null : this.getReleaseDownloaded().equals(other.getReleaseDownloaded()))
            && (this.getReleasePreview() == null ? other.getReleasePreview() == null : this.getReleasePreview().equals(other.getReleasePreview()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdRelease() == null) ? 0 : getIdRelease().hashCode());
        result = prime * result + ((getIdUser() == null) ? 0 : getIdUser().hashCode());
        result = prime * result + ((getReleaseDownloaded() == null) ? 0 : getReleaseDownloaded().hashCode());
        result = prime * result + ((getReleasePreview() == null) ? 0 : getReleasePreview().hashCode());
        return result;
    }
}