package it.fivano.symusic.backend.model;

import java.util.ArrayList;
import java.util.List;

public class ReleaseUserOptionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    public ReleaseUserOptionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdReleaseIsNull() {
            addCriterion("id_release is null");
            return (Criteria) this;
        }

        public Criteria andIdReleaseIsNotNull() {
            addCriterion("id_release is not null");
            return (Criteria) this;
        }

        public Criteria andIdReleaseEqualTo(Long value) {
            addCriterion("id_release =", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseNotEqualTo(Long value) {
            addCriterion("id_release <>", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseGreaterThan(Long value) {
            addCriterion("id_release >", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseGreaterThanOrEqualTo(Long value) {
            addCriterion("id_release >=", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseLessThan(Long value) {
            addCriterion("id_release <", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseLessThanOrEqualTo(Long value) {
            addCriterion("id_release <=", value, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseIn(List<Long> values) {
            addCriterion("id_release in", values, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseNotIn(List<Long> values) {
            addCriterion("id_release not in", values, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseBetween(Long value1, Long value2) {
            addCriterion("id_release between", value1, value2, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdReleaseNotBetween(Long value1, Long value2) {
            addCriterion("id_release not between", value1, value2, "idRelease");
            return (Criteria) this;
        }

        public Criteria andIdUserIsNull() {
            addCriterion("id_user is null");
            return (Criteria) this;
        }

        public Criteria andIdUserIsNotNull() {
            addCriterion("id_user is not null");
            return (Criteria) this;
        }

        public Criteria andIdUserEqualTo(Long value) {
            addCriterion("id_user =", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserNotEqualTo(Long value) {
            addCriterion("id_user <>", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserGreaterThan(Long value) {
            addCriterion("id_user >", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserGreaterThanOrEqualTo(Long value) {
            addCriterion("id_user >=", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserLessThan(Long value) {
            addCriterion("id_user <", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserLessThanOrEqualTo(Long value) {
            addCriterion("id_user <=", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserIn(List<Long> values) {
            addCriterion("id_user in", values, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserNotIn(List<Long> values) {
            addCriterion("id_user not in", values, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserBetween(Long value1, Long value2) {
            addCriterion("id_user between", value1, value2, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserNotBetween(Long value1, Long value2) {
            addCriterion("id_user not between", value1, value2, "idUser");
            return (Criteria) this;
        }

        public Criteria andReleaseDownloadedIsNull() {
            addCriterion("release_downloaded is null");
            return (Criteria) this;
        }

        public Criteria andReleaseDownloadedIsNotNull() {
            addCriterion("release_downloaded is not null");
            return (Criteria) this;
        }

        public Criteria andReleaseDownloadedEqualTo(Boolean value) {
            addCriterion("release_downloaded =", value, "releaseDownloaded");
            return (Criteria) this;
        }

        public Criteria andReleaseDownloadedNotEqualTo(Boolean value) {
            addCriterion("release_downloaded <>", value, "releaseDownloaded");
            return (Criteria) this;
        }

        public Criteria andReleaseDownloadedGreaterThan(Boolean value) {
            addCriterion("release_downloaded >", value, "releaseDownloaded");
            return (Criteria) this;
        }

        public Criteria andReleaseDownloadedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("release_downloaded >=", value, "releaseDownloaded");
            return (Criteria) this;
        }

        public Criteria andReleaseDownloadedLessThan(Boolean value) {
            addCriterion("release_downloaded <", value, "releaseDownloaded");
            return (Criteria) this;
        }

        public Criteria andReleaseDownloadedLessThanOrEqualTo(Boolean value) {
            addCriterion("release_downloaded <=", value, "releaseDownloaded");
            return (Criteria) this;
        }

        public Criteria andReleaseDownloadedIn(List<Boolean> values) {
            addCriterion("release_downloaded in", values, "releaseDownloaded");
            return (Criteria) this;
        }

        public Criteria andReleaseDownloadedNotIn(List<Boolean> values) {
            addCriterion("release_downloaded not in", values, "releaseDownloaded");
            return (Criteria) this;
        }

        public Criteria andReleaseDownloadedBetween(Boolean value1, Boolean value2) {
            addCriterion("release_downloaded between", value1, value2, "releaseDownloaded");
            return (Criteria) this;
        }

        public Criteria andReleaseDownloadedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("release_downloaded not between", value1, value2, "releaseDownloaded");
            return (Criteria) this;
        }

        public Criteria andReleasePreviewIsNull() {
            addCriterion("release_preview is null");
            return (Criteria) this;
        }

        public Criteria andReleasePreviewIsNotNull() {
            addCriterion("release_preview is not null");
            return (Criteria) this;
        }

        public Criteria andReleasePreviewEqualTo(Boolean value) {
            addCriterion("release_preview =", value, "releasePreview");
            return (Criteria) this;
        }

        public Criteria andReleasePreviewNotEqualTo(Boolean value) {
            addCriterion("release_preview <>", value, "releasePreview");
            return (Criteria) this;
        }

        public Criteria andReleasePreviewGreaterThan(Boolean value) {
            addCriterion("release_preview >", value, "releasePreview");
            return (Criteria) this;
        }

        public Criteria andReleasePreviewGreaterThanOrEqualTo(Boolean value) {
            addCriterion("release_preview >=", value, "releasePreview");
            return (Criteria) this;
        }

        public Criteria andReleasePreviewLessThan(Boolean value) {
            addCriterion("release_preview <", value, "releasePreview");
            return (Criteria) this;
        }

        public Criteria andReleasePreviewLessThanOrEqualTo(Boolean value) {
            addCriterion("release_preview <=", value, "releasePreview");
            return (Criteria) this;
        }

        public Criteria andReleasePreviewIn(List<Boolean> values) {
            addCriterion("release_preview in", values, "releasePreview");
            return (Criteria) this;
        }

        public Criteria andReleasePreviewNotIn(List<Boolean> values) {
            addCriterion("release_preview not in", values, "releasePreview");
            return (Criteria) this;
        }

        public Criteria andReleasePreviewBetween(Boolean value1, Boolean value2) {
            addCriterion("release_preview between", value1, value2, "releasePreview");
            return (Criteria) this;
        }

        public Criteria andReleasePreviewNotBetween(Boolean value1, Boolean value2) {
            addCriterion("release_preview not between", value1, value2, "releasePreview");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated do_not_delete_during_merge Fri Jan 03 15:41:40 CET 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}