package it.fivano.symusic.backend.model;

import java.io.Serializable;

public class ReleaseVideo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_video.id_release_video
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    private Long idReleaseVideo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_video.id_release
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    private Long idRelease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_video.video_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    private String videoLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table release_video
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_video.id_release_video
     *
     * @return the value of release_video.id_release_video
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public Long getIdReleaseVideo() {
        return idReleaseVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_video.id_release_video
     *
     * @param idReleaseVideo the value for release_video.id_release_video
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public void setIdReleaseVideo(Long idReleaseVideo) {
        this.idReleaseVideo = idReleaseVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_video.id_release
     *
     * @return the value of release_video.id_release
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public Long getIdRelease() {
        return idRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_video.id_release
     *
     * @param idRelease the value for release_video.id_release
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public void setIdRelease(Long idRelease) {
        this.idRelease = idRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_video.video_link
     *
     * @return the value of release_video.video_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public String getVideoLink() {
        return videoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_video.video_link
     *
     * @param videoLink the value for release_video.video_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public void setVideoLink(String videoLink) {
        this.videoLink = videoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_video
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ReleaseVideo other = (ReleaseVideo) that;
        return (this.getIdReleaseVideo() == null ? other.getIdReleaseVideo() == null : this.getIdReleaseVideo().equals(other.getIdReleaseVideo()))
            && (this.getIdRelease() == null ? other.getIdRelease() == null : this.getIdRelease().equals(other.getIdRelease()))
            && (this.getVideoLink() == null ? other.getVideoLink() == null : this.getVideoLink().equals(other.getVideoLink()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_video
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdReleaseVideo() == null) ? 0 : getIdReleaseVideo().hashCode());
        result = prime * result + ((getIdRelease() == null) ? 0 : getIdRelease().hashCode());
        result = prime * result + ((getVideoLink() == null) ? 0 : getVideoLink().hashCode());
        return result;
    }
}