package it.fivano.symusic.backend.model;

import java.io.Serializable;

public class UserPreference implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_preference.id_user_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    private Long idUserPreference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_preference.enable_beatport
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    private Boolean enableBeatport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_preference.id_user_preference
     *
     * @return the value of user_preference.id_user_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public Long getIdUserPreference() {
        return idUserPreference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_preference.id_user_preference
     *
     * @param idUserPreference the value for user_preference.id_user_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public void setIdUserPreference(Long idUserPreference) {
        this.idUserPreference = idUserPreference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_preference.enable_beatport
     *
     * @return the value of user_preference.enable_beatport
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public Boolean getEnableBeatport() {
        return enableBeatport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_preference.enable_beatport
     *
     * @param enableBeatport the value for user_preference.enable_beatport
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public void setEnableBeatport(Boolean enableBeatport) {
        this.enableBeatport = enableBeatport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserPreference other = (UserPreference) that;
        return (this.getIdUserPreference() == null ? other.getIdUserPreference() == null : this.getIdUserPreference().equals(other.getIdUserPreference()))
            && (this.getEnableBeatport() == null ? other.getEnableBeatport() == null : this.getEnableBeatport().equals(other.getEnableBeatport()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdUserPreference() == null) ? 0 : getIdUserPreference().hashCode());
        result = prime * result + ((getEnableBeatport() == null) ? 0 : getEnableBeatport().hashCode());
        return result;
    }
}