package it.fivano.symusic.backend.dao;

import it.fivano.symusic.backend.model.ReleaseExtraction;
import it.fivano.symusic.backend.model.ReleaseExtractionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReleaseExtractionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symusic..release_extraction
	 * @mbggenerated  Wed Oct 09 21:16:21 CEST 2013
	 */
	int countByExample(ReleaseExtractionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symusic..release_extraction
	 * @mbggenerated  Wed Oct 09 21:16:21 CEST 2013
	 */
	int deleteByExample(ReleaseExtractionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symusic..release_extraction
	 * @mbggenerated  Wed Oct 09 21:16:21 CEST 2013
	 */
	int deleteByPrimaryKey(Long idRelease);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symusic..release_extraction
	 * @mbggenerated  Wed Oct 09 21:16:21 CEST 2013
	 */
	int insert(ReleaseExtraction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symusic..release_extraction
	 * @mbggenerated  Wed Oct 09 21:16:21 CEST 2013
	 */
	int insertSelective(ReleaseExtraction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symusic..release_extraction
	 * @mbggenerated  Wed Oct 09 21:16:21 CEST 2013
	 */
	List<ReleaseExtraction> selectByExample(ReleaseExtractionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symusic..release_extraction
	 * @mbggenerated  Wed Oct 09 21:16:21 CEST 2013
	 */
	ReleaseExtraction selectByPrimaryKey(Long idRelease);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symusic..release_extraction
	 * @mbggenerated  Wed Oct 09 21:16:21 CEST 2013
	 */
	int updateByExampleSelective(@Param("record") ReleaseExtraction record,
			@Param("example") ReleaseExtractionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symusic..release_extraction
	 * @mbggenerated  Wed Oct 09 21:16:21 CEST 2013
	 */
	int updateByExample(@Param("record") ReleaseExtraction record,
			@Param("example") ReleaseExtractionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symusic..release_extraction
	 * @mbggenerated  Wed Oct 09 21:16:21 CEST 2013
	 */
	int updateByPrimaryKeySelective(ReleaseExtraction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symusic..release_extraction
	 * @mbggenerated  Wed Oct 09 21:16:21 CEST 2013
	 */
	int updateByPrimaryKey(ReleaseExtraction record);
}