package it.fivano.symusic.backend.dao;

import it.fivano.symusic.backend.model.ReleaseLink;
import it.fivano.symusic.backend.model.ReleaseLinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReleaseLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int countByExample(ReleaseLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int deleteByExample(ReleaseLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int deleteByPrimaryKey(Long idReleaseLink);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int insert(ReleaseLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int insertSelective(ReleaseLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    List<ReleaseLink> selectByExample(ReleaseLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    ReleaseLink selectByPrimaryKey(Long idReleaseLink);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int updateByExampleSelective(@Param("record") ReleaseLink record, @Param("example") ReleaseLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int updateByExample(@Param("record") ReleaseLink record, @Param("example") ReleaseLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int updateByPrimaryKeySelective(ReleaseLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_link
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int updateByPrimaryKey(ReleaseLink record);
}