package it.fivano.symusic.backend.dao;

import it.fivano.symusic.backend.model.ReleaseUserOption;
import it.fivano.symusic.backend.model.ReleaseUserOptionExample;
import it.fivano.symusic.backend.model.ReleaseUserOptionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReleaseUserOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    int countByExample(ReleaseUserOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    int deleteByExample(ReleaseUserOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    int deleteByPrimaryKey(ReleaseUserOptionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    int insert(ReleaseUserOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    int insertSelective(ReleaseUserOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    List<ReleaseUserOption> selectByExample(ReleaseUserOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    ReleaseUserOption selectByPrimaryKey(ReleaseUserOptionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    int updateByExampleSelective(@Param("record") ReleaseUserOption record, @Param("example") ReleaseUserOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    int updateByExample(@Param("record") ReleaseUserOption record, @Param("example") ReleaseUserOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    int updateByPrimaryKeySelective(ReleaseUserOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_user_option
     *
     * @mbggenerated Fri Jan 03 15:41:40 CET 2014
     */
    int updateByPrimaryKey(ReleaseUserOption record);
}