//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.02 at 10:00:04 AM CEST 
//


package it.fivano.symusic.jaxb.pagedef;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.fivano.symusic.jaxb.pagedef package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.fivano.symusic.jaxb.pagedef
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ElementSingle }
     * 
     */
    public ElementSingle createElementSingle() {
        return new ElementSingle();
    }

    /**
     * Create an instance of {@link ElementSingle.TagType }
     * 
     */
    public ElementSingle.TagType createElementSingleTagType() {
        return new ElementSingle.TagType();
    }

    /**
     * Create an instance of {@link ElementList }
     * 
     */
    public ElementList createElementList() {
        return new ElementList();
    }

    /**
     * Create an instance of {@link UrlParam.Value }
     * 
     */
    public UrlParam.Value createUrlParamValue() {
        return new UrlParam.Value();
    }

    /**
     * Create an instance of {@link UrlParam }
     * 
     */
    public UrlParam createUrlParam() {
        return new UrlParam();
    }

    /**
     * Create an instance of {@link Search }
     * 
     */
    public Search createSearch() {
        return new Search();
    }

    /**
     * Create an instance of {@link ElementList.TagType }
     * 
     */
    public ElementList.TagType createElementListTagType() {
        return new ElementList.TagType();
    }

    /**
     * Create an instance of {@link PageDefinition }
     * 
     */
    public PageDefinition createPageDefinition() {
        return new PageDefinition();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

}
