//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.02 at 10:00:04 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fivano.it/symusic/jaxb/pageDef", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.fivano.symusic.jaxb.pagedef;
