package it.fivano.symusic.backend.model;

import java.io.Serializable;

public class ReleaseVideo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column symusic..release_video.id_release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    private Long idReleaseVideo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column symusic..release_video.id_release
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    private Long idRelease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column symusic..release_video.video_link
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    private String videoLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column symusic..release_video.video_name
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    private String videoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column symusic..release_video.id_release_video
     *
     * @return the value of symusic..release_video.id_release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public Long getIdReleaseVideo() {
        return idReleaseVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column symusic..release_video.id_release_video
     *
     * @param idReleaseVideo the value for symusic..release_video.id_release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public void setIdReleaseVideo(Long idReleaseVideo) {
        this.idReleaseVideo = idReleaseVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column symusic..release_video.id_release
     *
     * @return the value of symusic..release_video.id_release
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public Long getIdRelease() {
        return idRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column symusic..release_video.id_release
     *
     * @param idRelease the value for symusic..release_video.id_release
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public void setIdRelease(Long idRelease) {
        this.idRelease = idRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column symusic..release_video.video_link
     *
     * @return the value of symusic..release_video.video_link
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public String getVideoLink() {
        return videoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column symusic..release_video.video_link
     *
     * @param videoLink the value for symusic..release_video.video_link
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public void setVideoLink(String videoLink) {
        this.videoLink = videoLink == null ? null : videoLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column symusic..release_video.video_name
     *
     * @return the value of symusic..release_video.video_name
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public String getVideoName() {
        return videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column symusic..release_video.video_name
     *
     * @param videoName the value for symusic..release_video.video_name
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    public void setVideoName(String videoName) {
        this.videoName = videoName == null ? null : videoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ReleaseVideo other = (ReleaseVideo) that;
        return (this.getIdReleaseVideo() == null ? other.getIdReleaseVideo() == null : this.getIdReleaseVideo().equals(other.getIdReleaseVideo()))
            && (this.getIdRelease() == null ? other.getIdRelease() == null : this.getIdRelease().equals(other.getIdRelease()))
            && (this.getVideoLink() == null ? other.getVideoLink() == null : this.getVideoLink().equals(other.getVideoLink()))
            && (this.getVideoName() == null ? other.getVideoName() == null : this.getVideoName().equals(other.getVideoName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release_video
     *
     * @mbggenerated Mon Sep 09 23:13:41 CEST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdReleaseVideo() == null) ? 0 : getIdReleaseVideo().hashCode());
        result = prime * result + ((getIdRelease() == null) ? 0 : getIdRelease().hashCode());
        result = prime * result + ((getVideoLink() == null) ? 0 : getVideoLink().hashCode());
        result = prime * result + ((getVideoName() == null) ? 0 : getVideoName().hashCode());
        return result;
    }
}