package it.fivano.symusic.backend.model;

import java.io.Serializable;
import java.util.Date;

public class Release implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column symusic..release.id_release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    private Long idRelease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column symusic..release.release_name
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    private String releaseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column symusic..release.author
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column symusic..release.song_name
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    private String songName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column symusic..release.years
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    private String years;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column symusic..release.crew
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    private String crew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column symusic..release.release_date
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    private Date releaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column symusic..release.id_genre
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    private Integer idGenre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column symusic..release.id_release
     *
     * @return the value of symusic..release.id_release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public Long getIdRelease() {
        return idRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column symusic..release.id_release
     *
     * @param idRelease the value for symusic..release.id_release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public void setIdRelease(Long idRelease) {
        this.idRelease = idRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column symusic..release.release_name
     *
     * @return the value of symusic..release.release_name
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public String getReleaseName() {
        return releaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column symusic..release.release_name
     *
     * @param releaseName the value for symusic..release.release_name
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public void setReleaseName(String releaseName) {
        this.releaseName = releaseName == null ? null : releaseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column symusic..release.author
     *
     * @return the value of symusic..release.author
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column symusic..release.author
     *
     * @param author the value for symusic..release.author
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column symusic..release.song_name
     *
     * @return the value of symusic..release.song_name
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public String getSongName() {
        return songName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column symusic..release.song_name
     *
     * @param songName the value for symusic..release.song_name
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public void setSongName(String songName) {
        this.songName = songName == null ? null : songName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column symusic..release.years
     *
     * @return the value of symusic..release.years
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public String getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column symusic..release.years
     *
     * @param years the value for symusic..release.years
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public void setYears(String years) {
        this.years = years == null ? null : years.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column symusic..release.crew
     *
     * @return the value of symusic..release.crew
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public String getCrew() {
        return crew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column symusic..release.crew
     *
     * @param crew the value for symusic..release.crew
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public void setCrew(String crew) {
        this.crew = crew == null ? null : crew.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column symusic..release.release_date
     *
     * @return the value of symusic..release.release_date
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column symusic..release.release_date
     *
     * @param releaseDate the value for symusic..release.release_date
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column symusic..release.id_genre
     *
     * @return the value of symusic..release.id_genre
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public Integer getIdGenre() {
        return idGenre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column symusic..release.id_genre
     *
     * @param idGenre the value for symusic..release.id_genre
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    public void setIdGenre(Integer idGenre) {
        this.idGenre = idGenre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Release other = (Release) that;
        return (this.getIdRelease() == null ? other.getIdRelease() == null : this.getIdRelease().equals(other.getIdRelease()))
            && (this.getReleaseName() == null ? other.getReleaseName() == null : this.getReleaseName().equals(other.getReleaseName()))
            && (this.getAuthor() == null ? other.getAuthor() == null : this.getAuthor().equals(other.getAuthor()))
            && (this.getSongName() == null ? other.getSongName() == null : this.getSongName().equals(other.getSongName()))
            && (this.getYears() == null ? other.getYears() == null : this.getYears().equals(other.getYears()))
            && (this.getCrew() == null ? other.getCrew() == null : this.getCrew().equals(other.getCrew()))
            && (this.getReleaseDate() == null ? other.getReleaseDate() == null : this.getReleaseDate().equals(other.getReleaseDate()))
            && (this.getIdGenre() == null ? other.getIdGenre() == null : this.getIdGenre().equals(other.getIdGenre()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symusic..release
     *
     * @mbggenerated Mon Sep 09 23:38:11 CEST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdRelease() == null) ? 0 : getIdRelease().hashCode());
        result = prime * result + ((getReleaseName() == null) ? 0 : getReleaseName().hashCode());
        result = prime * result + ((getAuthor() == null) ? 0 : getAuthor().hashCode());
        result = prime * result + ((getSongName() == null) ? 0 : getSongName().hashCode());
        result = prime * result + ((getYears() == null) ? 0 : getYears().hashCode());
        result = prime * result + ((getCrew() == null) ? 0 : getCrew().hashCode());
        result = prime * result + ((getReleaseDate() == null) ? 0 : getReleaseDate().hashCode());
        result = prime * result + ((getIdGenre() == null) ? 0 : getIdGenre().hashCode());
        return result;
    }
}