package it.fivano.symusic.backend.model;

import java.io.Serializable;

public class UserGenrePreference extends UserGenrePreferenceKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_genre_preference.rank
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_genre_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_genre_preference.rank
     *
     * @return the value of user_genre_preference.rank
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_genre_preference.rank
     *
     * @param rank the value for user_genre_preference.rank
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_genre_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserGenrePreference other = (UserGenrePreference) that;
        return (this.getIdGenre() == null ? other.getIdGenre() == null : this.getIdGenre().equals(other.getIdGenre()))
            && (this.getIdUser() == null ? other.getIdUser() == null : this.getIdUser().equals(other.getIdUser()))
            && (this.getRank() == null ? other.getRank() == null : this.getRank().equals(other.getRank()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_genre_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdGenre() == null) ? 0 : getIdGenre().hashCode());
        result = prime * result + ((getIdUser() == null) ? 0 : getIdUser().hashCode());
        result = prime * result + ((getRank() == null) ? 0 : getRank().hashCode());
        return result;
    }
}