package it.ivano.catalog.backend.dto;

// Generated 3-feb-2015 21.02.36 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Archivio generated by hbm2java
 */
@Entity
@Table(name = "archivio", catalog = "filecatalog")
public class Archivio implements java.io.Serializable {

	private Long idArchivio;
	private Utente utente;
	private String nome;
	private String descrizione;
	private String pathIniziale;
	private String dimensioneArchivio;
	private String spazioUtilizzato;
	private String spazioLibero;
	private Set<File> files = new HashSet<File>(0);
	private Set<Cartella> cartellas = new HashSet<Cartella>(0);

	public Archivio() {
	}

	public Archivio(Utente utente, String nome) {
		this.utente = utente;
		this.nome = nome;
	}

	public Archivio(Utente utente, String nome, String descrizione,
			String pathIniziale, String dimensioneArchivio,
			String spazioUtilizzato, String spazioLibero, Set<File> files,
			Set<Cartella> cartellas) {
		this.utente = utente;
		this.nome = nome;
		this.descrizione = descrizione;
		this.pathIniziale = pathIniziale;
		this.dimensioneArchivio = dimensioneArchivio;
		this.spazioUtilizzato = spazioUtilizzato;
		this.spazioLibero = spazioLibero;
		this.files = files;
		this.cartellas = cartellas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_archivio", unique = true, nullable = false)
	public Long getIdArchivio() {
		return this.idArchivio;
	}

	public void setIdArchivio(Long idArchivio) {
		this.idArchivio = idArchivio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_utente", nullable = false)
	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	@Column(name = "nome", nullable = false, length = 85)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descrizione", length = 500)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "path_iniziale", length = 500)
	public String getPathIniziale() {
		return this.pathIniziale;
	}

	public void setPathIniziale(String pathIniziale) {
		this.pathIniziale = pathIniziale;
	}

	@Column(name = "dimensione_archivio", length = 45)
	public String getDimensioneArchivio() {
		return this.dimensioneArchivio;
	}

	public void setDimensioneArchivio(String dimensioneArchivio) {
		this.dimensioneArchivio = dimensioneArchivio;
	}

	@Column(name = "spazio_utilizzato", length = 45)
	public String getSpazioUtilizzato() {
		return this.spazioUtilizzato;
	}

	public void setSpazioUtilizzato(String spazioUtilizzato) {
		this.spazioUtilizzato = spazioUtilizzato;
	}

	@Column(name = "spazio_libero", length = 45)
	public String getSpazioLibero() {
		return this.spazioLibero;
	}

	public void setSpazioLibero(String spazioLibero) {
		this.spazioLibero = spazioLibero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "archivio")
	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "archivio")
	public Set<Cartella> getCartellas() {
		return this.cartellas;
	}

	public void setCartellas(Set<Cartella> cartellas) {
		this.cartellas = cartellas;
	}

}
