package it.ivano.catalog.backend.dto;

// Generated 3-feb-2015 21.53.09 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FileMusica generated by hbm2java
 */
@Entity
@Table(name = "file_musica", catalog = "filecatalog")
public class FileMusica implements java.io.Serializable {

	private Long idFileMusica;
	private File file;
	private String codecAudio;
	private String bitrate;
	private String artista;
	private String traccia;
	private String album;
	private String anno;
	private String numeroTraccia;
	private String durata;
	private String genere;
	private Date ripDate;
	private String ripCrew;

	public FileMusica() {
	}

	public FileMusica(File file) {
		this.file = file;
	}

	public FileMusica(File file, String codecAudio, String bitrate,
			String artista, String traccia, String album, String anno,
			String numeroTraccia, String durata, String genere, Date ripDate,
			String ripCrew) {
		this.file = file;
		this.codecAudio = codecAudio;
		this.bitrate = bitrate;
		this.artista = artista;
		this.traccia = traccia;
		this.album = album;
		this.anno = anno;
		this.numeroTraccia = numeroTraccia;
		this.durata = durata;
		this.genere = genere;
		this.ripDate = ripDate;
		this.ripCrew = ripCrew;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_file_musica", unique = true, nullable = false)
	public Long getIdFileMusica() {
		return this.idFileMusica;
	}

	public void setIdFileMusica(Long idFileMusica) {
		this.idFileMusica = idFileMusica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_file", nullable = false)
	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	@Column(name = "codec_audio", length = 45)
	public String getCodecAudio() {
		return this.codecAudio;
	}

	public void setCodecAudio(String codecAudio) {
		this.codecAudio = codecAudio;
	}

	@Column(name = "bitrate", length = 15)
	public String getBitrate() {
		return this.bitrate;
	}

	public void setBitrate(String bitrate) {
		this.bitrate = bitrate;
	}

	@Column(name = "artista", length = 400)
	public String getArtista() {
		return this.artista;
	}

	public void setArtista(String artista) {
		this.artista = artista;
	}

	@Column(name = "traccia", length = 500)
	public String getTraccia() {
		return this.traccia;
	}

	public void setTraccia(String traccia) {
		this.traccia = traccia;
	}

	@Column(name = "album", length = 500)
	public String getAlbum() {
		return this.album;
	}

	public void setAlbum(String album) {
		this.album = album;
	}

	@Column(name = "anno", length = 4)
	public String getAnno() {
		return this.anno;
	}

	public void setAnno(String anno) {
		this.anno = anno;
	}

	@Column(name = "numero_traccia", length = 8)
	public String getNumeroTraccia() {
		return this.numeroTraccia;
	}

	public void setNumeroTraccia(String numeroTraccia) {
		this.numeroTraccia = numeroTraccia;
	}

	@Column(name = "durata", length = 15)
	public String getDurata() {
		return this.durata;
	}

	public void setDurata(String durata) {
		this.durata = durata;
	}

	@Column(name = "genere", length = 45)
	public String getGenere() {
		return this.genere;
	}

	public void setGenere(String genere) {
		this.genere = genere;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rip_date", length = 10)
	public Date getRipDate() {
		return this.ripDate;
	}

	public void setRipDate(Date ripDate) {
		this.ripDate = ripDate;
	}

	@Column(name = "rip_crew", length = 100)
	public String getRipCrew() {
		return this.ripCrew;
	}

	public void setRipCrew(String ripCrew) {
		this.ripCrew = ripCrew;
	}

}
