package it.ivano.catalog.backend.dto;

// Generated 3-feb-2015 21.53.09 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FileVideoAudio generated by hbm2java
 */
@Entity
@Table(name = "file_video_audio", catalog = "filecatalog")
public class FileVideoAudio implements java.io.Serializable {

	private int idFileVideoAudio;
	private FileVideo fileVideo;
	private String descrizione;
	private String codec;
	private String bitrate;
	private String canali;
	private String linguaggio;

	public FileVideoAudio() {
	}

	public FileVideoAudio(int idFileVideoAudio, FileVideo fileVideo) {
		this.idFileVideoAudio = idFileVideoAudio;
		this.fileVideo = fileVideo;
	}

	public FileVideoAudio(int idFileVideoAudio, FileVideo fileVideo,
			String descrizione, String codec, String bitrate, String canali,
			String linguaggio) {
		this.idFileVideoAudio = idFileVideoAudio;
		this.fileVideo = fileVideo;
		this.descrizione = descrizione;
		this.codec = codec;
		this.bitrate = bitrate;
		this.canali = canali;
		this.linguaggio = linguaggio;
	}

	@Id
	@Column(name = "id_file_video_audio", unique = true, nullable = false)
	public int getIdFileVideoAudio() {
		return this.idFileVideoAudio;
	}

	public void setIdFileVideoAudio(int idFileVideoAudio) {
		this.idFileVideoAudio = idFileVideoAudio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_file_video", nullable = false)
	public FileVideo getFileVideo() {
		return this.fileVideo;
	}

	public void setFileVideo(FileVideo fileVideo) {
		this.fileVideo = fileVideo;
	}

	@Column(name = "descrizione")
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "codec", length = 50)
	public String getCodec() {
		return this.codec;
	}

	public void setCodec(String codec) {
		this.codec = codec;
	}

	@Column(name = "bitrate", length = 10)
	public String getBitrate() {
		return this.bitrate;
	}

	public void setBitrate(String bitrate) {
		this.bitrate = bitrate;
	}

	@Column(name = "canali", length = 5)
	public String getCanali() {
		return this.canali;
	}

	public void setCanali(String canali) {
		this.canali = canali;
	}

	@Column(name = "linguaggio", length = 45)
	public String getLinguaggio() {
		return this.linguaggio;
	}

	public void setLinguaggio(String linguaggio) {
		this.linguaggio = linguaggio;
	}

}
