package it.ivano.catalog.backend.dto;
// Generated 3-feb-2015 21.53.09 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FileImage generated by hbm2java
 */
@Entity
@Table(name="file_image"
    ,catalog="filecatalog"
)
public class FileImage  implements java.io.Serializable {


     private Long idFileImage;
     private File file;
     private Date dataAcquisizione;
     private Integer altezza;
     private Integer larghezza;
     private String risoluzioneOrizzontale;
     private String risoluzioneVerticale;
     private String fotocamera;
     private String FStop;
     private String iso;
     private String esposizione;

    public FileImage() {
    }

	
    public FileImage(File file) {
        this.file = file;
    }
    public FileImage(File file, Date dataAcquisizione, Integer altezza, Integer larghezza, String risoluzioneOrizzontale, String risoluzioneVerticale, String fotocamera, String FStop, String iso, String esposizione) {
       this.file = file;
       this.dataAcquisizione = dataAcquisizione;
       this.altezza = altezza;
       this.larghezza = larghezza;
       this.risoluzioneOrizzontale = risoluzioneOrizzontale;
       this.risoluzioneVerticale = risoluzioneVerticale;
       this.fotocamera = fotocamera;
       this.FStop = FStop;
       this.iso = iso;
       this.esposizione = esposizione;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_file_image", unique=true, nullable=false)
    public Long getIdFileImage() {
        return this.idFileImage;
    }
    
    public void setIdFileImage(Long idFileImage) {
        this.idFileImage = idFileImage;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_file", nullable=false)
    public File getFile() {
        return this.file;
    }
    
    public void setFile(File file) {
        this.file = file;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_acquisizione", length=19)
    public Date getDataAcquisizione() {
        return this.dataAcquisizione;
    }
    
    public void setDataAcquisizione(Date dataAcquisizione) {
        this.dataAcquisizione = dataAcquisizione;
    }

    
    @Column(name="altezza")
    public Integer getAltezza() {
        return this.altezza;
    }
    
    public void setAltezza(Integer altezza) {
        this.altezza = altezza;
    }

    
    @Column(name="larghezza")
    public Integer getLarghezza() {
        return this.larghezza;
    }
    
    public void setLarghezza(Integer larghezza) {
        this.larghezza = larghezza;
    }

    
    @Column(name="risoluzione_orizzontale", length=15)
    public String getRisoluzioneOrizzontale() {
        return this.risoluzioneOrizzontale;
    }
    
    public void setRisoluzioneOrizzontale(String risoluzioneOrizzontale) {
        this.risoluzioneOrizzontale = risoluzioneOrizzontale;
    }

    
    @Column(name="risoluzione_verticale", length=15)
    public String getRisoluzioneVerticale() {
        return this.risoluzioneVerticale;
    }
    
    public void setRisoluzioneVerticale(String risoluzioneVerticale) {
        this.risoluzioneVerticale = risoluzioneVerticale;
    }

    
    @Column(name="fotocamera", length=100)
    public String getFotocamera() {
        return this.fotocamera;
    }
    
    public void setFotocamera(String fotocamera) {
        this.fotocamera = fotocamera;
    }

    
    @Column(name="f_stop", length=15)
    public String getFStop() {
        return this.FStop;
    }
    
    public void setFStop(String FStop) {
        this.FStop = FStop;
    }

    
    @Column(name="iso", length=15)
    public String getIso() {
        return this.iso;
    }
    
    public void setIso(String iso) {
        this.iso = iso;
    }

    
    @Column(name="esposizione", length=15)
    public String getEsposizione() {
        return this.esposizione;
    }
    
    public void setEsposizione(String esposizione) {
        this.esposizione = esposizione;
    }




}


