package it.ivano.catalog.backend.dto;

// Generated 3-feb-2015 21.53.09 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * File generated by hbm2java
 */
@Entity
@Table(name = "file", catalog = "filecatalog")
public class File implements java.io.Serializable {

	private Long idFile;
	private Archivio archivio;
	private Cartella cartella;
	private MimeType mimeType;
	private String fileName;
	private String estensione;
	private Date ultimaModifica;
	private String dimensione;
	private Date dataInserimento;
	private Date dataUltimoAggiornamento;
	private Boolean flagCancellazione;
	private int eliminato;
	private Date dataUltimaLettura;
	private Set<FileVideo> fileVideos = new HashSet<FileVideo>(0);
	private Set<FileImage> fileImages = new HashSet<FileImage>(0);
	private Set<FileMusica> fileMusicas = new HashSet<FileMusica>(0);

	public File() {
	}

	public File(Archivio archivio, Cartella cartella, String fileName,
			int eliminato) {
		this.archivio = archivio;
		this.cartella = cartella;
		this.fileName = fileName;
		this.eliminato = eliminato;
	}

	public File(Archivio archivio, Cartella cartella, MimeType mimeType,
			String fileName, String estensione, Date ultimaModifica,
			String dimensione, Date dataInserimento,
			Date dataUltimoAggiornamento, Boolean flagCancellazione,
			int eliminato, Date dataUltimaLettura, Set<FileVideo> fileVideos,
			Set<FileImage> fileImages, Set<FileMusica> fileMusicas) {
		this.archivio = archivio;
		this.cartella = cartella;
		this.mimeType = mimeType;
		this.fileName = fileName;
		this.estensione = estensione;
		this.ultimaModifica = ultimaModifica;
		this.dimensione = dimensione;
		this.dataInserimento = dataInserimento;
		this.dataUltimoAggiornamento = dataUltimoAggiornamento;
		this.flagCancellazione = flagCancellazione;
		this.eliminato = eliminato;
		this.dataUltimaLettura = dataUltimaLettura;
		this.fileVideos = fileVideos;
		this.fileImages = fileImages;
		this.fileMusicas = fileMusicas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_file", unique = true, nullable = false)
	public Long getIdFile() {
		return this.idFile;
	}

	public void setIdFile(Long idFile) {
		this.idFile = idFile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_archivio", nullable = false)
	public Archivio getArchivio() {
		return this.archivio;
	}

	public void setArchivio(Archivio archivio) {
		this.archivio = archivio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cartella", nullable = false)
	public Cartella getCartella() {
		return this.cartella;
	}

	public void setCartella(Cartella cartella) {
		this.cartella = cartella;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_mime_type")
	public MimeType getMimeType() {
		return this.mimeType;
	}

	public void setMimeType(MimeType mimeType) {
		this.mimeType = mimeType;
	}

	@Column(name = "file_name", nullable = false, length = 400)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "estensione", length = 15)
	public String getEstensione() {
		return this.estensione;
	}

	public void setEstensione(String estensione) {
		this.estensione = estensione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ultima_modifica", length = 19)
	public Date getUltimaModifica() {
		return this.ultimaModifica;
	}

	public void setUltimaModifica(Date ultimaModifica) {
		this.ultimaModifica = ultimaModifica;
	}

	@Column(name = "dimensione", length = 45)
	public String getDimensione() {
		return this.dimensione;
	}

	public void setDimensione(String dimensione) {
		this.dimensione = dimensione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inserimento", length = 19)
	public Date getDataInserimento() {
		return this.dataInserimento;
	}

	public void setDataInserimento(Date dataInserimento) {
		this.dataInserimento = dataInserimento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_ultimo_aggiornamento", length = 19)
	public Date getDataUltimoAggiornamento() {
		return this.dataUltimoAggiornamento;
	}

	public void setDataUltimoAggiornamento(Date dataUltimoAggiornamento) {
		this.dataUltimoAggiornamento = dataUltimoAggiornamento;
	}

	@Column(name = "flag_cancellazione")
	public Boolean getFlagCancellazione() {
		return this.flagCancellazione;
	}

	public void setFlagCancellazione(Boolean flagCancellazione) {
		this.flagCancellazione = flagCancellazione;
	}

	@Column(name = "eliminato", nullable = false)
	public int getEliminato() {
		return this.eliminato;
	}

	public void setEliminato(int eliminato) {
		this.eliminato = eliminato;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_ultima_lettura", length = 19)
	public Date getDataUltimaLettura() {
		return this.dataUltimaLettura;
	}

	public void setDataUltimaLettura(Date dataUltimaLettura) {
		this.dataUltimaLettura = dataUltimaLettura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "file")
	public Set<FileVideo> getFileVideos() {
		return this.fileVideos;
	}

	public void setFileVideos(Set<FileVideo> fileVideos) {
		this.fileVideos = fileVideos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "file")
	public Set<FileImage> getFileImages() {
		return this.fileImages;
	}

	public void setFileImages(Set<FileImage> fileImages) {
		this.fileImages = fileImages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "file")
	public Set<FileMusica> getFileMusicas() {
		return this.fileMusicas;
	}

	public void setFileMusicas(Set<FileMusica> fileMusicas) {
		this.fileMusicas = fileMusicas;
	}

}
