package it.ivano.catalog.backend.dto;

// Generated 3-feb-2015 21.53.09 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FileVideo generated by hbm2java
 */
@Entity
@Table(name = "file_video", catalog = "filecatalog")
public class FileVideo implements java.io.Serializable {

	private Long idFileVideo;
	private File file;
	private String formato;
	private String anno;
	private String larghezza;
	private String altezza;
	private String aspectRatio;
	private String durata;
	private String codecVideo;
	private String frameRate;
	private Set<FileVideoAudio> fileVideoAudios = new HashSet<FileVideoAudio>(0);

	public FileVideo() {
	}

	public FileVideo(File file) {
		this.file = file;
	}

	public FileVideo(File file, String formato, String anno, String larghezza,
			String altezza, String aspectRatio, String durata,
			String codecVideo, String frameRate,
			Set<FileVideoAudio> fileVideoAudios) {
		this.file = file;
		this.formato = formato;
		this.anno = anno;
		this.larghezza = larghezza;
		this.altezza = altezza;
		this.aspectRatio = aspectRatio;
		this.durata = durata;
		this.codecVideo = codecVideo;
		this.frameRate = frameRate;
		this.fileVideoAudios = fileVideoAudios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_file_video", unique = true, nullable = false)
	public Long getIdFileVideo() {
		return this.idFileVideo;
	}

	public void setIdFileVideo(Long idFileVideo) {
		this.idFileVideo = idFileVideo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_file", nullable = false)
	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	@Column(name = "formato", length = 50)
	public String getFormato() {
		return this.formato;
	}

	public void setFormato(String formato) {
		this.formato = formato;
	}

	@Column(name = "anno", length = 4)
	public String getAnno() {
		return this.anno;
	}

	public void setAnno(String anno) {
		this.anno = anno;
	}

	@Column(name = "larghezza", length = 10)
	public String getLarghezza() {
		return this.larghezza;
	}

	public void setLarghezza(String larghezza) {
		this.larghezza = larghezza;
	}

	@Column(name = "altezza", length = 10)
	public String getAltezza() {
		return this.altezza;
	}

	public void setAltezza(String altezza) {
		this.altezza = altezza;
	}

	@Column(name = "aspect_ratio", length = 15)
	public String getAspectRatio() {
		return this.aspectRatio;
	}

	public void setAspectRatio(String aspectRatio) {
		this.aspectRatio = aspectRatio;
	}

	@Column(name = "durata", length = 15)
	public String getDurata() {
		return this.durata;
	}

	public void setDurata(String durata) {
		this.durata = durata;
	}

	@Column(name = "codec_video", length = 45)
	public String getCodecVideo() {
		return this.codecVideo;
	}

	public void setCodecVideo(String codecVideo) {
		this.codecVideo = codecVideo;
	}

	@Column(name = "frame_rate", length = 15)
	public String getFrameRate() {
		return this.frameRate;
	}

	public void setFrameRate(String frameRate) {
		this.frameRate = frameRate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fileVideo")
	public Set<FileVideoAudio> getFileVideoAudios() {
		return this.fileVideoAudios;
	}

	public void setFileVideoAudios(Set<FileVideoAudio> fileVideoAudios) {
		this.fileVideoAudios = fileVideoAudios;
	}

}
