package it.ivano.catalog.backend.dto;
// Generated 3-feb-2015 21.53.09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MimeType generated by hbm2java
 */
@Entity
@Table(name="mime_type"
    ,catalog="filecatalog"
    , uniqueConstraints = @UniqueConstraint(columnNames="mime_type") 
)
public class MimeType  implements java.io.Serializable {


     private Long idMimeType;
     private String area;
     private String subArea;
     private String mimeType;
     private String listaEstensioni;
     private int flagTipoBase;
     private Set<File> files = new HashSet<File>(0);

    public MimeType() {
    }

	
    public MimeType(String area, String mimeType, String listaEstensioni, int flagTipoBase) {
        this.area = area;
        this.mimeType = mimeType;
        this.listaEstensioni = listaEstensioni;
        this.flagTipoBase = flagTipoBase;
    }
    public MimeType(String area, String subArea, String mimeType, String listaEstensioni, int flagTipoBase, Set<File> files) {
       this.area = area;
       this.subArea = subArea;
       this.mimeType = mimeType;
       this.listaEstensioni = listaEstensioni;
       this.flagTipoBase = flagTipoBase;
       this.files = files;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_mime_type", unique=true, nullable=false)
    public Long getIdMimeType() {
        return this.idMimeType;
    }
    
    public void setIdMimeType(Long idMimeType) {
        this.idMimeType = idMimeType;
    }

    
    @Column(name="area", nullable=false, length=45)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

    
    @Column(name="sub_area", length=45)
    public String getSubArea() {
        return this.subArea;
    }
    
    public void setSubArea(String subArea) {
        this.subArea = subArea;
    }

    
    @Column(name="mime_type", unique=true, nullable=false, length=100)
    public String getMimeType() {
        return this.mimeType;
    }
    
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    
    @Column(name="lista_estensioni", nullable=false, length=80)
    public String getListaEstensioni() {
        return this.listaEstensioni;
    }
    
    public void setListaEstensioni(String listaEstensioni) {
        this.listaEstensioni = listaEstensioni;
    }

    
    @Column(name="flag_tipo_base", nullable=false)
    public int getFlagTipoBase() {
        return this.flagTipoBase;
    }
    
    public void setFlagTipoBase(int flagTipoBase) {
        this.flagTipoBase = flagTipoBase;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mimeType")
    public Set<File> getFiles() {
        return this.files;
    }
    
    public void setFiles(Set<File> files) {
        this.files = files;
    }




}


