package it.ivano.catalog.backend.dto;

// Generated 3-feb-2015 21.53.09 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utente generated by hbm2java
 */
@Entity
@Table(name = "utente", catalog = "filecatalog")
public class Utente implements java.io.Serializable {

	private Long idUtente;
	private String nome;
	private String cognome;
	private String email;
	private String password;
	private int abilitato;
	private Set<Archivio> archivios = new HashSet<Archivio>(0);
	private Set<ConfigUtente> configUtentes = new HashSet<ConfigUtente>(0);

	public Utente() {
	}

	public Utente(String nome, String cognome, String email, String password,
			int abilitato) {
		this.nome = nome;
		this.cognome = cognome;
		this.email = email;
		this.password = password;
		this.abilitato = abilitato;
	}

	public Utente(String nome, String cognome, String email, String password,
			int abilitato, Set<Archivio> archivios,
			Set<ConfigUtente> configUtentes) {
		this.nome = nome;
		this.cognome = cognome;
		this.email = email;
		this.password = password;
		this.abilitato = abilitato;
		this.archivios = archivios;
		this.configUtentes = configUtentes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_utente", unique = true, nullable = false)
	public Long getIdUtente() {
		return this.idUtente;
	}

	public void setIdUtente(Long idUtente) {
		this.idUtente = idUtente;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "cognome", nullable = false, length = 100)
	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 150)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "abilitato", nullable = false)
	public int getAbilitato() {
		return this.abilitato;
	}

	public void setAbilitato(int abilitato) {
		this.abilitato = abilitato;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utente")
	public Set<Archivio> getArchivios() {
		return this.archivios;
	}

	public void setArchivios(Set<Archivio> archivios) {
		this.archivios = archivios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utente")
	public Set<ConfigUtente> getConfigUtentes() {
		return this.configUtentes;
	}

	public void setConfigUtentes(Set<ConfigUtente> configUtentes) {
		this.configUtentes = configUtentes;
	}

}
